const { PERMISSIONS, ALL_PERMISSIONS } = require("./permissions");

const ROLE_ALIASES = Object.freeze({
  admin: "ADMIN", ADMIN: "ADMIN",
  manager: "HR_MANAGER", HR_MANAGER: "HR_MANAGER",
  supervisor: "SUPERVISOR", SUPERVISOR: "SUPERVISOR",
  employee: "EMPLOYEE", EMPLOYEE: "EMPLOYEE",
  user: "EMPLOYEE", User: "EMPLOYEE",
});

const HR_MANAGER_PERMISSIONS = [
  PERMISSIONS.USERS_READ,
  PERMISSIONS.EMPLOYEES_READ, PERMISSIONS.EMPLOYEES_WRITE, PERMISSIONS.EMPLOYEES_DELETE,
  PERMISSIONS.EMPLOYEES_IMPORT, PERMISSIONS.EMPLOYEES_EXPORT,
  PERMISSIONS.ORG_READ, PERMISSIONS.ORG_WRITE,
  PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE, PERMISSIONS.ATTENDANCE_APPROVE,
  PERMISSIONS.LEAVES_READ, PERMISSIONS.LEAVES_WRITE, PERMISSIONS.LEAVES_APPROVE,
  PERMISSIONS.PAYROLL_READ, PERMISSIONS.PAYROLL_WRITE, PERMISSIONS.PAYROLL_GENERATE, PERMISSIONS.PAYROLL_APPROVE,
  PERMISSIONS.REPORTS_READ, PERMISSIONS.ANALYTICS_READ, PERMISSIONS.AUDIT_READ,
  PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_WRITE,
  PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.DOCUMENTS_WRITE,
  PERMISSIONS.ANNOUNCEMENTS_READ, PERMISSIONS.ANNOUNCEMENTS_WRITE,
  PERMISSIONS.SHIFTS_READ, PERMISSIONS.SHIFTS_WRITE,
  PERMISSIONS.WORKFLOWS_READ, PERMISSIONS.WORKFLOWS_WRITE, PERMISSIONS.WORKFLOWS_APPROVE,
  PERMISSIONS.RECRUITMENT_READ, PERMISSIONS.RECRUITMENT_WRITE,
  PERMISSIONS.ONBOARDING_READ, PERMISSIONS.ONBOARDING_WRITE,
  PERMISSIONS.OFFBOARDING_READ, PERMISSIONS.OFFBOARDING_WRITE,
  PERMISSIONS.REPORTS_SCHEDULE,
  PERMISSIONS.BENEFITS_READ, PERMISSIONS.BENEFITS_WRITE,
  PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_WRITE,
  PERMISSIONS.PERFORMANCE_READ, PERMISSIONS.PERFORMANCE_WRITE,
  PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_WRITE,
];

const SYSTEM_ROLES = Object.freeze({
  ADMIN: {
    key: "ADMIN", name: "Administrator", description: "Full organization access",
    permissions: ALL_PERMISSIONS, isSystem: true,
  },
  HR_MANAGER: {
    key: "HR_MANAGER", name: "HR Manager", description: "Manage HR operations",
    permissions: HR_MANAGER_PERMISSIONS, isSystem: true,
  },
  SUPERVISOR: {
    key: "SUPERVISOR", name: "Supervisor", description: "Department team oversight",
    permissions: [
      PERMISSIONS.EMPLOYEES_READ, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE,
      PERMISSIONS.ATTENDANCE_APPROVE, PERMISSIONS.LEAVES_READ, PERMISSIONS.LEAVES_WRITE,
      PERMISSIONS.LEAVES_APPROVE, PERMISSIONS.REPORTS_READ, PERMISSIONS.WORKFLOWS_APPROVE,
      PERMISSIONS.SHIFTS_READ, PERMISSIONS.PERFORMANCE_READ,
    ],
    isSystem: true,
  },
  EMPLOYEE: {
    key: "EMPLOYEE", name: "Employee", description: "Self-service portal",
    permissions: [
      PERMISSIONS.ESS_ACCESS, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.LEAVES_READ,
      PERMISSIONS.LEAVES_WRITE, PERMISSIONS.PAYROLL_READ, PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.DOCUMENTS_WRITE, PERMISSIONS.ANNOUNCEMENTS_READ, PERMISSIONS.TRAINING_READ,
      PERMISSIONS.PERFORMANCE_READ,
    ],
    isSystem: true,
  },
});

function normalizeRoleKey(role) {
  if (!role) return "EMPLOYEE";
  return ROLE_ALIASES[role] || ROLE_ALIASES[String(role).toLowerCase()] || "EMPLOYEE";
}

function getPermissionsForRole(roleKey) {
  const key = normalizeRoleKey(roleKey);
  const role = SYSTEM_ROLES[key];
  return role ? [...role.permissions] : [...SYSTEM_ROLES.EMPLOYEE.permissions];
}

function roleHasPermission(roleKey, permission) {
  return getPermissionsForRole(roleKey).includes(permission);
}

/** Department-scoped access for supervisors viewing department resources. */
function canAccessDepartment(user, resourceDepartmentId) {
  if (!user) return false;
  const role = normalizeRoleKey(user.role);
  if (role === "ADMIN" || role === "HR_MANAGER") return true;
  if (!resourceDepartmentId || !user.departmentId) return role !== "SUPERVISOR";
  return String(user.departmentId) === String(resourceDepartmentId);
}

module.exports = {
  SYSTEM_ROLES, ROLE_ALIASES, normalizeRoleKey, getPermissionsForRole,
  roleHasPermission, canAccessDepartment,
};
